name: Lint + Prettier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-prettier:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint + prettier Application
      -  run: |
          yarn install --frozen-lockfile
          yarn lint
